[source]
type = "N2N"
peers = ["preprod-node.world.dev.cardano.org:30000"]

[chain]
type = "preprod"

[intersect]
type = "Tip"

[[filters]]
type = "LegacyV1"
include_transaction_details = true

[[filters]]
type = "Deno"
main_module = "oura/filter.js"
use_async = true

[sink]
type = "WebHook"
url = "http://localhost:4202/api/updateOrder"
timeout = 30000
error_policy = "Continue"

[sink.retry_policy]
max_retries = 30
backoff_unit = 5000
backoff_factor = 2
max_backoff = 100000
